version: '3'
services:
  api_gateway:
    container_name: api-gateway
    build:
      context: .
      dockerfile: Dockerfile-api
    restart: always
    environment:
      - SERVER_PORT=3000
      - SERVER_TIMEOUT=60
    ports:
      - 3000:3000
    networks:
      - EpyphiteNet
    depends_on:
      - postgresdb
  
  postgresdb:
    image: postgres:latest
    container_name: postgres_container
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - DATABASE_HOST=${DB_HOST}
    volumes:
      - ./scripts/dbInit:/docker-entrypoint-initdb.d/:ro
    ports:
      - '5432:5432'
    networks:
      - EpyphiteNet

networks:
  EpyphiteNet:
