version: '3'
services:
  postgresdb:
    image: postgres:latest
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - ./scripts/dbInit:/docker-entrypoint-initdb.d/:ro
    ports:
      - '5432:5432'
    networks:
      - EpyphiteNet

  api_gateway:
    build:
      context: .
      dockerfile: Dockerfile-api
    restart: always
    environment:
      - SERVER_PORT=3000
      - SERVER_TIMEOUT=60
      - DB_DSN=${DB_DRIVER}://${DB_USER}:${DB_PASSWORD}@${DB_HOST}:${DB_PORT}/${DB_NAME}?sslmode=disable&timezone=UTC
      - DB_MIN_POOL=1
      - DB_MAX_POOL=10
      - OPENWEATHER_APIKEY=${OPENWEATHER_APIKEY}
    ports:
      - 3000:3000
    networks:
      - EpyphiteNet
    depends_on:
      - postgresdb

  cronjob:
    build:
      context: .
      dockerfile: Dockerfile-cron
    restart: always
    networks:
      - EpyphiteNet
    depends_on:
      - api_gateway

networks:
  EpyphiteNet:
