FROM golang:1.23-alpine

WORKDIR /build
COPY . .
RUN go mod download
RUN go get -u github.com/swaggo/swag
RUN go build -o ./api-gateway ./cmd/api-gateway/main.go

FROM alpine:latest  
RUN apk --no-cache add ca-certificates
COPY --from=builder /build/api-gateway ./api-gateway
COPY --from=builder /build/config ./config

CMD ["./api-gateway"]
